name: Test

on: pull_request

env:
  REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
  REACT_APP_API_CLIENT_ID: ${{ secrets.REACT_APP_API_CLIENT_ID }}
  REACT_APP_API_CLIENT_SECRET: ${{ secrets.REACT_APP_API_CLIENT_SECRET }}

jobs:
  test:
    name: Run linters and tests
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node and restore cached dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run codebase:lint

      - name: Run unit tests
        run: npm test -- --coverage

      - name: Run integration tests
        run: npm run cypress

      - name: Merge code coverage reports
        run: npm run test:merge-coverage

      - name: Danger
        run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
